### ISSUE TITLE
Horusec analysis failed: Command failed:

### ISSUE THREAD

**Issue by wtlinnertz** [ZupIT/horusec-vscode-plugin#36]
When I first run the analysis after installing the extension (v1.9 and v1.8) it says it starts but never return anything and eventually the status message at the bottom of VS Code goes away.  If I try to start another analysis, I get the following error.

Horusec analysis failed: Command failed: docker run -v //var/run/docker.sock:/var/run/docker.sock -v //c//Users//zzz//wsl:/src/horusec-vscode --name horusec-cli horuszup/horusec-cli:v1.10.3 horusec start -p /src/horusec-vscode -P //c//Users//zzz//wsl -o json -O /src/horusec-vscode/horusec-result.json --config-file-path /src/horusec-vscode/horusec-config.json -I true
docker: Error response from daemon: Conflict. The container name "/horusec-cli" is already in use by container "7c8c3564948412a9c030ef92fb314dbde91b5f3f46d656080230449c25c421ee". You have to remove (or rename) that container to be able to reuse that name.

If I manually remove the container and start an analysis, the same cycle repeats.

**Comment by nathannascimentozup** [comment]
Hi @wtlinnertz thanks for reporting.

can you tell us which version of vscode and which operating system are you trying to run the analysis?

**Comment by nathanmartinszup** [comment]
Hi @wtlinnertz. 

We found and fixed the [issue](https://github.com/ZupIT/horusec-vscode-plugin/pull/37). A new version of the plugin was published and is available.

Contact us if you have any other problem, we will be happy to help.

Thanks for your feedback! It is of great help so that we can evolve.
